# Generated by Django 5.2 on 2025-07-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasetfile",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("csv", "Comma-Separated Values"),
                    ("geojson", "GeoJSON"),
                    ("html", "HTML"),
                    ("json", "JSON Object"),
                    ("kml", "KML (GeoXML)"),
                    ("other", "Other File Type"),
                    ("parquet", "Parquet Database"),
                    ("shp", "Shapefile"),
                    ("sqlite", "SQLite Database"),
                    ("tsv", "Tab-Separated Values"),
                    ("xls", "Excel Spreadsheet"),
                    ("xml", "XML File"),
                ]
            ),
        ),
    ]
