# Generated by Django 5.2 on 2025-07-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_datasetfile_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetfile',
            name='file_type',
            field=models.CharField(choices=[('csv', 'Comma-Separated Values'), ('esri rest', 'ESRI REST API File'), ('geojson', 'GeoJSON'), ('html', 'HTML'), ('json', 'JSON Object'), ('kml', 'KML (GeoXML)'), ('mxd', 'ArcGIS MXD File'), ('other', 'Other File Type'), ('parquet', 'Parquet Database'), ('pdf', 'PDF (Portable Document Format)'), ('shp', 'Shapefile'), ('sqlite', 'SQLite Database'), ('tsv', 'Tab-Separated Values'), ('xls', 'Excel Spreadsheet'), ('xml', 'XML File')]),
        ),
    ]
