# Generated by Django 5.2 on 2025-07-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_alter_datasetfile_file_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasetfile",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("csv", "Comma-Separated Values"),
                    ("edi", "Electronic Data Interchange"),
                    ("esri rest", "ESRI REST API File"),
                    ("fgdb/gdb", "File Geodatabase"),
                    ("geojson", "GeoJSON"),
                    ("geotif", "GeoTIFF"),
                    ("html", "HTML"),
                    ("json", "JSON Object"),
                    ("kml", "KML (GeoXML)"),
                    ("kmz", "Keyhole Markup Language KMZ"),
                    ("mxd", "ArcGIS MXD File"),
                    ("other", "Other File Type"),
                    ("parquet", "Parquet Database"),
                    ("pdf", "PDF (Portable Document Format)"),
                    ("shp", "Shapefile"),
                    ("sqlite", "SQLite Database"),
                    ("tiff", "Tag Image File Format"),
                    ("tsv", "Tab-Separated Values"),
                    ("wms", "ArcGIS Web Map Service"),
                    ("xls", "Excel Spreadsheet"),
                    ("xlsx", "Excel Open XML Spreadsheet"),
                    ("xml", "XML File"),
                ]
            ),
        ),
    ]
