# Generated by Django 5.2 on 2025-09-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0014_alter_dataset_scraper"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetfile",
            name="last_mirrored",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="datasetfile",
            name="mirrored_url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="publisher",
            name="mirror",
            field=models.BooleanField(default=False),
        ),
    ]
