# Generated by Django 5.2 on 2025-09-04 02:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0014_alter_dataset_scraper"),
        ("catalog", "0015_alter_dataset_end_date_alter_dataset_start_date"),
    ]

    operations = []
