# Generated by Django 5.2 on 2025-09-16 16:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0015_datasetfile_last_mirrored_datasetfile_mirrored_url_and_more"),
        ("catalog", "0016_merge_20250904_0233"),
    ]

    operations = []
