# Generated by Django 5.2 on 2025-09-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0017_merge_20250916_1649"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasetfile",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("csv", "CSV"),
                    ("fgdb/gdb", "File Geodatabase"),
                    ("geojson", "GeoJSON"),
                    ("json", "JSON Object"),
                    ("kml", "KML (GeoXML)"),
                    ("other", "Other File Type"),
                    ("other-geo", "Other Geo File Type"),
                    ("parquet", "Parquet Database"),
                    ("shp", "Shapefile"),
                    ("sqlite", "SQLite Database"),
                    ("tsv", "Tab-Separated Values"),
                    ("xls", "Excel Spreadsheet"),
                    ("xlsx", "Excel Open XML Spreadsheet"),
                    ("xml", "XML File"),
                ]
            ),
        ),
    ]
