# Generated by Django 5.2 on 2025-09-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_ingestionrecord_dataset_identifier_kinds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestionrecord',
            name='cleardb',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ingestionrecord',
            name='ingest_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ingestionrecord',
            name='run_finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingestionrecord',
            name='status',
            field=models.CharField(blank=True, choices=[('s', 'Success'), ('fs', 'Failed: scraper failure'), ('fd', 'Failed: write to database failure')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ingestionrecord',
            name='status_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
